### ISSUE TITLE
RFC: Class based jobs

### ISSUE THREAD

**Issue by McSneaky** [cavai-research/Adonis-Queue#27]
## Description

After running to some limitations with using this queue in more complex system. Figured that class-based approach would help to make it more powerful

Whole idea is to learn from Laravel Queue and go with similar approach

So there will be job classes, something like this (really pseudocode)
```ts
export default class MyJob extends BaseJob {
    // Allow queue override
    protected queue = this.config.queue || 'my_default_queue'

    // Allow delaying jobs for x time
    protected delay = this.config.delay || 0
    
    constructor(protected payload, protected config) { }
    
    public async handle() {
        // Handle job
        console.log('Job started with payload:')
        console.log(this.payload)

        await new Promise(res => setTimeout(() => res(true), 500))
        console.log('Job finished!')
    }

    /** Runs when job fails */ 
    protected async onError(error) {
        // Might keep that to future improvements and not add it straight away
        Logger.warn(`Job ${this.constructor.name} failed!`)
        Logger.warn(error)
    }
}
```

Dispatching job would look something like this:
```ts
// Basic dispatch
MyJob.dispatch({ pay: 'load' })
// Dispatch with delay / config
MyJob.dispatch({ pay: 'load' }, { delay: DateTime.now().addMinutes(5) })
// Or function based delay (more Laravel like)
MyJob.dispatch({ pay: 'load' }).delay(DateTime.now().addMinutes(5))
```

I'm still not sure if should use constructor based config, dispatch param based config or separate functions
```ts
// Examples of overwriting default queue where job should be added

// Constructor based
(new MyJob({ queue: 'mail_queue' })).dispatch({ pay: 'load' })
// Dispatch based
MyJob().dispatch({ pay: 'load' }, { queue: 'mail_queue' })
// Or separate function
MyJob().dispatch({ pay: 'load' }).queue('mail_queue')
```

Would also like to add database queue driver and maybe drop Redis one for now
Database driver is quite powerful and it's easy to deploy, since most applications already have DB anyway, so there's no need to deploy anything new (like Redis)

For starters I'd start working on database and then in-memory syncronous driver (for testing)
Database one would build on top of Knex / Lucid. There's additional chance of improvement in future to use database changefeeds, but that required different driver for different DBs
Database driver should come with job locks right outta box, so multiple executors don't pick up same job

Having class based jobs it should be possible to add TypeScript definitions for them too, so you get nice intellisense out of it

Any ideas / comments, suggestions etc are welcome!

I'll start slowly hacking on it and see where I end up 🙂

**Comment by McSneaky** [comment]
Another thing..
Should make it with `delay` to delay job for x time
 or `runAt` and try to run job at given timestamp
or `notBefore` and run job not before given timestamp. It's basically the same as `runAt`. Just `runAt` would make you think it runs exactly at that timestamp, but in case there are many jobs queued for same time and just single executor there will be delies 

Looking at Laravel queue they use `delay` and it's most likely coz of some good reason :)

**Comment by Melchyore** [comment]
- I think that if you opt for a class-based approach, the Queue manager should not be used anymore.

- Chaining methods is better in my opinion than passing configs as second argument for methods like `delay` and `dispatch`. Better readability.

- I don't understand why you should drop Redis, is it so difficult to implement? I think people should have the choice to use whatever they want and you should even add more drivers (like SQS from Amazon 😛).

- `delay` is enough I think. If one wants to run a job at specific (date)time, a cron job is the solution. I mean, it's a queue, it's unpredictable. When you'are in a queue to buy something or to get a paper, do you know when is your turn? No, you just have a ticket number and you wait.

- Support for DB transactions (even when using drivers other than DB) [https://laravel.com/docs/9.x/queues#jobs-and-database-transactions](https://laravel.com/docs/9.x/queues#jobs-and-database-transactions).

- `onQueue` instead of `queue`.

- A rate limiter for the jobs.

- Support for middleware? [https://laravel.com/docs/9.x/queues#preventing-job-overlaps](https://laravel.com/docs/9.x/queues#preventing-job-overlaps).

- Other cool features from Laravel Queues.

If you want it to be like Laravel, you have to get out the big game 😋😋

**Comment by McSneaky** [comment]
> I think that if you opt for a class-based approach, the Queue manager should not be used anymore. Or it should no longer have methods like use, extend, etc.

Jup, want to get rid of those too

> I don't understand why you should drop Redis, is it so difficult to implement? I think people should have the choice to use whatever they want and you should even add more drivers (like SQS from Amazon 😛).

Just because time is limited. Planning to start with DB and Memory (maybe), then add Redis, SQS, etc down the road. Ofc can always extend it yourself adding custom drivers. Would be nice tho if "official" ones would be DB, memory (sync), Redis and SQS. Those seem to be the most used ones, but have to start with 1 or 2

> Support for DB transactions (even when using drivers other than DB) https://laravel.com/docs/9.x/queues#jobs-and-database-transactions.

I have to look into this one, but from initial look it seems to be overcoming PHP process forking issues, which we shouldn't need in Node at all. Will look deeper into it

> Other cool features from Laravel Queues.

Yeah, will add them slowly, but have to start out small. It took years for Laravel to build queue they have right now, there's no way we'll build something like that overnight in Node, even when we can learn from all their learnings

Checked initial version of Laravel queue and went thro their changelog yesterday
At first release they had only `Queue::push('JobName', payload)` (kinda like this package current version) and that's about it. There wasn't even automatic job deletion after job ran. You had to remove it from DB manually 😋

**Comment by Melchyore** [comment]
Of course, it's not easy to implement something in a short period of time even if it already exists in another language. When I created the Cache module for AdonisJS, it took me almost 4 months to implement (not all) the features from Laravel.

And yeah, Laravel is old, they didn't have the knowledge we have today nor the tools. But "you had to remove the job manually from the DB" would really f*ck me up. 😂😂

Anyway, if you need some help, feel free to PM me on Discord.

**Comment by McSneaky** [comment]
Closing since done in https://github.com/cavai-research/Adonis-Queue/pull/28
