### ISSUE TITLE
Jobs are duplicated if you run multiple tasks

### ISSUE THREAD

**Issue by jilik** [cavai-research/Adonis-Queue#32]
I start multiple node ace queue:start
SQL = 'SELECT * FROM "adonis_jobs" WHERE "available_at" < ? AND "failed" = ? LIMIT ? FOR UPDATE skip locked'
I have duplicate jobs
The database works with transactions
They are blocked if this is done from the client

**Comment by McSneaky** [comment]
Fixed in latest version 2.0.5: https://github.com/cavai-research/Adonis-Queue/releases/tag/v2.0.5
