### ISSUE TITLE
How to start in production

### ISSUE THREAD

**Issue by palfaro91** [cavai-research/Adonis-Queue#40]
Is there an example of starting the queue in a production server?

**Comment by McSneaky** [comment]
`node ace queue:start`

How to keep it running is up to you and your operating system. You can use `pm2`, `screen`, `tmux`, `systemd`, `Start-process`, `Invoke-Command` to mention some

**Comment by thiagopinto** [comment]
Hey how's it going?

How do I create parallel queues?

example: I have 8 processes for sending emails (using pm2) and I want to have 1 process checking the returns (aws SAS).

I want one village not to wait for the other.

**Comment by thiagopinto** [comment]
I thought it was..

queues: {
    database: {
      driver: 'database',
      tableName: 'adonis_jobs',
      pollingDelay: 500,
    },
   feedback: {
     driver: 'database',
     tableName: 'feedback_jobs',
     pollingDelay: 1000,
   }
},

node ace queue:start feedback

**Comment by thiagopinto** [comment]
how to associate classJob ex:

export default class EmailFeedback extends BaseJob {} 


how to associate the classJob with the feedback queue?

**Comment by McSneaky** [comment]
> How do I create parallel queues?

You can start it multiple times with `npm run queue:start` or `npm run queue:start queueName`

> how to associate the classJob with the feedback queue?

You can't assign class in class declaration, but you can decide to which queue to add it with `useQueue(queueName)` when dispatching jobs

```ts
EmailFeedback.useQueue('feedback').dispatch()
```

Closing issue, since it's not related to running in prod, which got resolved
